-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 20, 2020 at 04:48 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `obati`
--

-- --------------------------------------------------------

--
-- Table structure for table `drug`
--

CREATE TABLE `drug` (
  `id` int(3) NOT NULL,
  `name` varchar(40) NOT NULL,
  `category` varchar(20) NOT NULL,
  `price` int(30) NOT NULL,
  `description` varchar(500) NOT NULL,
  `dose` varchar(500) NOT NULL,
  `howto` varchar(500) NOT NULL,
  `pic` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `drug`
--

INSERT INTO `drug` (`id`, `name`, `category`, `price`, `description`, `dose`, `howto`, `pic`) VALUES
(1, 'Sangobion 10 Tablet', 'Vitamin & suplemen', 13000, 'Untuk penyakit anemia', '1 kapsul, sekali sehari.', 'Tinggal minum', './assets/img/obat/test.jpg'),
(2, 'Pharmaton Formula 5 Kapsul', 'Vitamin & suplemen', 24000, 'PHARMATON FORMULA merupakan kombinasi dari multivitamin, mineral dan ekstrak gingseng yang digunakan untuk menjaga stamina dan kesehatan tubuh setelah operasi dan pada masa pemulihan.\r\nKategori', 'Dewasa: 1x sehari 1 kapsul lunak', 'Sewaktu makan', './assets/img/obat/test.jpg'),
(3, 'Enervon-C 30 TABLET', 'Vitamin & suplemen', 33000, 'ENERVON C merupakan suplemen makanan dengan kandungan multivitamin seperti Vitamin C, Vitamin B1, Vitamin B2, Vitamin B6, Vitamin B12, Vitamin D, Niasinamide, Kalsium pantotenat dalam bentuk tablet salut. Suplemen vitamin ini berguna untuk membantu menjaga daya tahan tubuh. Kombinasi vitamin C dan B komplek yang diperlukan untuk tubuh yang kekurangan vitamin, supaya daya tahan tubuh tetap terjaga serta membantu memulihkan kondisi setelah sakit.', '1 tablet per hari', 'Sebelum atau sesudah makan, dapat bersama makanan untuk absorpsi yang lebih baik.', './assets/img/obat/test.jpg'),
(4, 'Blackmores Vitamin C 500 MG 60 Tablet', 'Vitamin & suplemen', 20000, 'BLACKMORES VITAMIN C 500 MG merupakan suplemen yang menganding vitamin C yang diperlukan untuk memelihara kesehatan tubuh, menjaga daya tahan tubuh terhadap radikal bebas.', 'Dewasa: 1 tablet sehari setelah makan, atau sesuai petunjuk dokter.', 'Dapat dikonsumsi Sesudah makan', './assets/img/obat/test.jpg'),
(5, 'Vitacimin rasa Lemon 500 MG 20 Tablet', 'Vitamin & suplemen', 11000, 'VITACIMIN merupakan obat dengan kandungan Ascorbic acid dalam bentuk tablet hisap. Obat ini digunakan untuk membantu memenuhi kebutuhan vitamin c.', '1-2 tablet/hari', 'Diberikan bersama dengan makanan', './assets/img/obat/test.jpg'),
(6, 'Bisolvon Extra Sirup', 'Batuk & Flu', 41900, 'BISOLVON EXTRA SIRUP mengandung Bromhexine HCl dan Guaiphenesin, digunakan untuk mengatasi batuk berdahak dengan cara mengencerkan dahak dan mempermudah pengeluaran dahak pada saat batuk.', 'Dewasa dan anak >12 tahun : 3 kali sehari 10 mL. Anak 6-12 tahun : 3 kali sehari 5 mL. Anak 2-6 tahun : 3 kali sehari 2.5 mL.', 'Berikan sesudah makan\r\n', './assets/img/obat/bisolvonextrasirup.jpg'),
(7, 'Paratusin 10 Tablet', 'Batuk & Flu', 13700, 'PARATUSIN merupakan obat dengan kandungan Noscapine, chlorpheniramine maleate, glyceryl guaiacolate, paracetamol, dan phenylpropanolamine HCl. Obat ini digunakan untuk meringankan gejala-gejala flu seperti demam, sakit kepala, hidung tersumbat dan bersin-bersin yang disertai batuk. Paratusin bekerja sebagai analgetik-antipiretik, antitusif, ekspektoran, antihistamin dan dekongestan hidung.\r\n', 'Dewasa: 3 kali sehari 1 tablet. Anak (6 - 12 tahun) : 3 kali sehari 1/2 tablet.\r\n', 'Obat diminum sesudah makan\r\n', './assets/img/obat/paratusin10tablet.jpg'),
(8, 'Alpara 10 Kaplet', 'Batuk & Flu', 7700, 'ALPARA KAPLET merupakan obat dengan kandungan Paracetamol, Phenylpropanolamine HCl, Klorfeniramin Maleat, dan Dextromethorphan HBr. Obat ini dapat digunakan untuk meringankan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin-bersin yang disertai batuk. Alpara kaplet bekerja sebagai analgetik-antipiretik, dekongestan hidung, antihistamin, ekspektoran dan antitusif.', 'Dewasa dan diatas 12 tahun : 3 kali sehari 1 kaplet. Anak 6-12 tahun : 3 kali sehari 1/2 kaplet', 'Sesudah makan', './assets/img/obat/alpara10kaplet.jpg'),
(9, 'Ambroxol 30 MG 10 Tablet', 'Batuk & Flu', 2800, 'AMBROXOL merupakan obat batuk berdahak yang berfungsi sebagai mukolitik. Obat ini bekerja dengan cara mengencerkan dahak sehingga mudah dikeluarkan saat batuk. Obat ini digunakan untuk penyakit-penyakit pada saluran pernafasan dimana terjadi banyak lendir atau dahak, seperti : emfisema, radang paru kronis, bronkiektasis, eksaserbasi bronkitis kronis dan akut, bronkitis asmatik, asma bronkial yang disertai kesukaran pengeluaran dahak, serta penyakit radang rinofaringeal.', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 1 tablet, 2-3 x per hari. Anak 6-12 tahun : 0.5 tablet, 2-3 x per hari.', 'Sesudah makan', './assets/img/obat/ambroxol30mg.jpg'),
(10, 'Rhinos SR 10 Kapsul\r\n', 'Batuk & Flu', 68900, 'AMBROXOL merupakan obat batuk berdahak yang berfungsi sebagai mukolitik. Obat ini bekerja dengan cara mengencerkan dahak sehingga mudah dikeluarkan saat batuk. Obat ini digunakan untuk penyakit-penyakit pada saluran pernafasan dimana terjadi banyak lendir atau dahak, seperti : emfisema, radang paru kronis, bronkiektasis, eksaserbasi bronkitis kronis dan akut, bronkitis asmatik, asma bronkial yang disertai kesukaran pengeluaran dahak, serta penyakit radang rinofaringeal. Dalam penggunaan obat ini', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 1 tablet, 2-3 x per hari. Anak 6-12 tahun : 0.5 tablet, 2-3 x per hari.', 'Diminum sebelum atau sesudah makan', './assets/img/obat/rhinossr10.jpg'),
(11, 'Panadol 500 MG 10 Kaplet', 'Demam', 9900, 'PANADOL merupakan obat dengan kandungan Paracetamol 500 mg. Obat ini dapat digunakan untuk meredakan sakit kepala, sakit gigi, sakit pada otot, nyeri yang mengganggu dan menurunkan demam yang menyertai flu/influensa dan demam sesudah vaksinasi. Panadol bekerja pada pusat pengatur suhu di hipotalamus untuk menurunkan suhu tubuh (antipiretik) serta menghambat sintesis prostaglandin sehingga dapat mengurangi nyeri ringan sampai sedang.\r\n', '1 kapsul, sekali sehari.', 'Tinggal minum', './assets/img/obat/test.jpg'),
(12, 'Biogesic 500 MG', 'Demam', 2100, 'BIOGESIC merupakan obat dengan kandungan Paracetamol 500 mg. Obat ini dapat digunakan untuk meredakan demam, dismenorea, gangguan muskuloskeletal, sakit kepala, sakit gigi, dan arthritis\r\n', '1 kapsul, sekali sehari.', 'Tinggal minum', './assets/img/obat/test.jpg'),
(13, 'Biogesic 500 MG', 'Demam', 4000, 'BIOGESIC merupakan obat dengan kandungan Paracetamol 500 mg. Obat ini dapat digunakan untuk meredakan demam, dismenorea, gangguan muskuloskeletal, sakit kepala, sakit gigi, dan arthritis\r\n', 'Dewasa: 1 - 2 kaplet, 3 sampai 4 kali per hari. Penggunaan maximum 8 kaplet per hari. Anak (7 - 12 tahun): 0.5 - 1 kaplet, 3 sampai 4 kali per hari. Penggunaan maximum 4 kaplet per hari.\r\n', 'Tinggal minum', './assets/img/obat/test.jpg'),
(14, 'Dumin 500 MG', 'Demam', 9900, 'DUMIN merupakan obat dengan kandungan Paracetamol 500 mg. Obat ini dapat digunakan untuk meredakan nyeri seperti sakit kepala, sakit gigi, nyeri otot dan demam.\r\n', 'Dewasa: 1 - 2 kaplet, 3 sampai 4 kali per hari. Penggunaan maximum 8 kaplet per hari. Anak (7 - 12 tahun): 1/2 - 1 kaplet, 3 sampai 4 kali per hari. Penggunaan maximum 4 kaplet per hari.\r\n', 'Obat dapat diminum sebelum atau sesudah makan\r\n', './assets/img/obat/test.jpg'),
(15, 'Proris 200 MG 10 Kaplet', 'Demam', 8000, 'PRORIS TABLET merupakan obat dengan kandungan Ibuprofen 200 mg. Obat ini digunakan untuk meredakan nyeri ringan sampai sedang, dan sakit kepala. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa bengkak & nyeri : 3-4 kali sehari 400mg. Nyeri : 3-4 kali sehari 200-400mg, maks. 2400mg/hari. Anak (8 - 12 tahun): 3-4 kali sehari 200mg. Anak (3 - 7 tahun) : 3-4 kali sehari 100mg. Anak (1 - 2 tahun) : 3-4 kali sehari 50mg.\r\n', 'minum sesudah makan', './assets/img/obat/test.jpg'),
(16, 'Mefinal 500 MG 10 Tablet', 'Anti Nyeri', 15800, 'MEFINAL 500 MG merupakan obat dengan kandungan Asam Mefenamat yang termasuk dalam golongan anti infalamasi non steroid sebagai anti nyeri pada tingkat ringan hingga sedang. Obat ini dapat digunakan untuk meredakan sakit kepala, sakit gigi, nyeri haid, nyeri akibat trauma, nyeri pada otot dan nyeri sesudah operasi.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dosis dewasa dan anak usia lebih dari 14 tahun : Dosis awal 500 mg, kemudian dilanjutkan 250 mg tiap 6 jam, sesuai dengan kebutuhan.', 'Dikonsumsi sesudah makan.', './assets/img/obat/test.jpg'),
(17, 'Natrium Diklofenak 25 MG 10 Tablet', 'Anti Nyeri', 10500, 'NATRIUM DIKLOFENAK 25 MG TABLET adalah obat yang di gunakan sebagai pereda nyeri, mengurangi gangguan inflamasi, dismenore, nyeri ringan sampai sedang pasca operasi khususnya ketika pasien mengalami peradangan. Voltaren mengandung diklofenak adalah golongan no steroid anti inflamasi (NSAID)', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa dan Anak diatas 12 tahun: 1 tablet, 2 sampai 3 kali per hari.', 'Sesudah makan', './assets/img/obat/test.jpg'),
(18, 'VOLTAREN EMULGEL 5 G', 'Anti Nyeri', 55900, 'VOLTAREN EMULGEL merupakan sediaan topikal yang mengandung zat aktif Diclofenac dan digunakan untuk mengatasi peradangan akibat trauma tendon, ligamen, otot dan sendi. Obat ini juga digunakan untuk mengatasi reumatisme jaringan lunak dan penyakit reumatik.', '3-4 kali sehari', 'Oleskan ke tempat yang sakit', './assets/img/obat/test.jpg'),
(19, 'Mertigo 6 MG 10 TABLET', 'Anti Nyeri', 40800, 'MERTIGO 6 MG TABLET merupakan obat dengan kandungan Betahistine Mesylate 6 mg per tablet. Betahistine adalah suatu analog histamin dan dapat mengurangi tekanan endolimfatik dengan cara memperbaiki mikrosirkulasi.', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 3 x sehari 1-2 tablet', 'Sesudah makan', './assets/img/obat/test.jpg'),
(20, 'NEURALGIN RX 10 KAPLET', 'Anti Nyeri', 23400, 'NEURALGIN RX merupakan obat dengan kandungan Methampyron, Thiamin HCl, Pyridoxine HCl, Cyanocobalamine, Trimethylxantine. Obat ini ditujukan untuk pengobatan pada dismenore primer, meredakan nyeri ringan hingga sedang, meredakan gejala dan tanda osteoarthritis, meredakan gejala dan tanda rheumatoid arthritis.', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 3-4 x sehari 1-2 kaplet, Anak : 3-4 x sehari 0.5-1 kaplet.', 'Sesudah makan', './assets/img/obat/test.jpg'),
(21, 'Cendo Cenfresh Minidose 0.6 ML', 'Mata', 28800, 'CENDO CENFRESH mengandung Carboxymethylcellulose Sodium merupakan tetes mata yang digunakan untuk membantu mengurangi iritasi pada mata yang kering serta membantu mengurangi rasa tidak nyaman karena matahari dan angin.', '1-2 tetes pada mata yang sakit. Diteteskan 3-4 kali sehari atau sesuai kebutuhan.', 'Teteskan pada mata yang sakit. Jangan digunakan lebih dari 3 hari setelah wadah dibuka.', './assets/img/obat/test.jpg'),
(22, 'Erlamycetin 1% Salep Mata 3.5 G', 'Mata', 8200, 'ERLAMYCETIN 1% SALEP MATA adalah salep antibiotik steril untuk mata yang mengandung Chloramphenicol 1%. Chloramphenicol adalah antibiotik spektrum luas yang bersifat bakteriostatik. Obat ini efektif terhadap bakteri gram positif dan gram negatif yang aerob dan anaerob, kecuali Pseudomonas aeruginosa. ', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. oleskan 3 kali sehari', 'oleskan pada mata yang sakit', './assets/img/obat/test.jpg'),
(23, 'Insto Dry Eyes 7.5 ML', 'Mata', 14200, 'NSTO DRY EYES mengandung zat aktif Hidroxyprophylmethyl selulose dan Benzalkonium Chloride, digunakan untuk mengatasi gejala kekeringan pada mata dengan memberikan efek pelumas seperti air mata.', '1-2 tetes pada setiap mata, 3 kali sehari', 'teteskan pada mata yang sakit', './assets/img/obat/test.jpg'),
(24, 'Terracymin Salep Mata 3.5 G', 'Mata', 13200, 'TERRAMYCIN SALEP MATA adalah salep mata antibiotik yang mengandung Oxytetracycline 1%. Obat ini efektif untuk trakoma dan infeksi lain pada mata oleh kuman gram positif dan gram negatif yang sensitif. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dioleskan pada mata 2 - 4 kali per hari.', 'Salep dioleskan pada mata yang sakit', './assets/img/obat/test.jpg'),
(25, 'Visine Original Eye Drops 6 ML', 'Mata', 15200, 'VISINE ORIGINAL EYE DROP merupakan tetes mata steril yang mengandung zat aktif Tetrahidrozolin HCl. Tetes mata ini dapat meredakan mata merah karena iritasi mata yang ringan, seperti iritasi oleh debu, asap, terkena sengatan matahari atau iritasi setelah berenang.', '1-2 tetes pada setiap mata sebanyak 2-3 kali sehari atau sesuai petunjuk dokter.', 'Diteteskan pada mata yang merah. Agar tidak terkontaminasi, jagalah supaya ujung botol tidak terkena tangan atau benda-benda lain. Tutuplah kembali botol setelah digunakan.', './assets/img/obat/test.jpg'),
(26, 'Degirol Hisap 0.25 MG 10 Tablet', 'Mulut & Tenggorokan', 8800, 'DEGIROL merupakan tablet hisap yang mengandung Dequalinium Chloride. Obat ini digunakan untuk mengobati sakit tenggorokan, radang pada rongga mulut dan tenggorokan, serta infeksi selaput lendir mulut.\r\n', 'Dewasa: 1 tablet dihisap, tiap 3 - 4 jam. Maksimal 8 tablet per hari', 'Satu tablet dibiarkan melarut perlahan-lahan di dalam mulut.', './assets/img/obat/degirol.jpg'),
(27, 'Betadine Obat Kumur 190 ML', 'Mulut & Tenggorokan', 19000, 'BETADINE OBAT KUMUR 190 ML mengandung zat aktif Povidone iodine, obat kumur ini digunakan untuk mengatasi masalah mulut seperti sakit tenggorokan, gusi bengkak, sariawan, bau mulut dan napas tidak segar.\r\n', 'Kumur selama 30 detik, lakukan 3-5 kali per hari, atau sesuai kebutuhan.', 'tuangkan Betadine obat kumur 15 ml pada tutup botol dan kumurlah selama 30- 60 detik.', './assets/img/obat/betadineobatkumur.jpg'),
(28, 'Aloclair Plus Gel 8 ML', 'Mulut & Tenggorokan', 84000, 'ALOCLAIR PLUS merupakan obat pereda nyeri yang bekerja secara cepat dan membantu penyembuhan pada ulkus rongga mulut. Obat ini mengandung aloe vera dan asam hialuronat.\r\n', 'Aplikasikan 1-2 cm pada area yang sakit, 3-4 kali sehari', 'Dioleskan pada luka iritasi pada mulut', './assets/img/obat/aloclair.jpg'),
(29, 'Hexadol Gargle 120 ML\r\n', 'Mulut & Tenggorokan', 84000, 'HEXADOL merupakan obat yang memiliki kandungan Hexetidine dalam bentuk larutan. Hextidine mmerupakan zat yang bersifat sebagai antiseptik yang dapat digunakan untuk membasmi bakteri (gram positif dan negatif) dan jamur. Obat ini digunakan untuk infeksi ringan pada mulut dan teggorokan (radang gusi, sariawan, radang selaput lendir mulut, gejala radang tenggorokan, radang amandel), pembilas sebelum dan sesudah pencabutan gigi, menjaga kebersihan mulut sesudah operasi.\r\n', 'Kumur 15 ml selama 30 detik pagi dan malam', 'Untuk luka oada laosan mukosa mulut dan tenggorokan: 15 ml dikumurkan selama 30 detik pada pagi dan malam hari, atau oleskan dengan kapas lidi pada luka.', './assets/img/obat/hexadol.jpg'),
(30, 'Dentasol Drop 10 ML', 'Mulut & Tenggorokan', 9000, 'DENTASOL DROP 10 ML adalah obat gigi berbentuk cair untuk meredakan sakit gigi, peradangan gusi, sariawan serta masalah pada gigi, gusi dan mulut lainnya. Dentasol mengandung benzocain, cetylpyridium chloride, campora, mentholum, phenolum\r\n', 'Oleskan dengan kapas diulangi setiap 3-4 jam\r\n', 'Oleskan pada tempat yang sakit', './assets/img/obat/dentasol.jpg'),
(31, 'Allopurinol 100 MG 10 Tablet\r\n', 'Otot, Tulang & Sendi', 12400, 'ALLOPURINOL 100 MG TABLET adalah obat generik yang digunakan untuk menurunkan kadar asam urat dalam darah. Obat ini bekerja dengan cara menghambat enzim xanthine oksidase sehingga mengurangi pembentukan asam urat dan juga dapat menghambat sintesis purin. Enzim xanthine oksidase adalah enzim yang bertanggung jawab untuk oksidasi hypoxanthine dan xanthine. Obat ini digunakan untuk pencegahan serangan gout kronis, mengobati sindrom lisis tumor dalam kemoterapi karena kemoterapi sering menyebabkan t', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 1 tablet, 1 kali sehari Dosis per hari : 100-300 mg per hari, sesuai dengan tingkat keparahan penyakit.\r\n', 'Diminum sebelum atau sesudah makan', './assets/img/obat/allopurinol.jpg'),
(32, 'Myonal 50 MG 10 Tablet\r\n', 'Otot, Tulang & Sendi', 84800, 'MYONAL 50 MG TABLET merupakan obat dengan kandungan Eperisone HCl 50 mg per tablet. Eperisone adalah obat antispasmodik yang bekerja sebagai relaksan otot/melemaskan otot rangka dan otot polos vaskular, yang menghasilkan pengurangan myotonia, peningkatan sirkulasi, dan penekanan refleks rasa sakit. Obat ini digunakan untuk pengobatan simtomatik terhadap kondisi yang terkait dengan spasme muskuloskeletal/kejang otot. Dalam penggunaan obat ini HARUS SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : 3 x sehari 1 tablet\r\n', 'Sesudah makan\r\n', './assets/img/obat/myonal50mg.jpg'),
(33, 'Zyloric 100 MG 10 Tablet\r\n', 'Otot, Tulang & Sendi', 60500, 'ZYLORIC 100 MG TABLET merupakan obat dengan kandungan Allopurinol 100 mg per tablet. Allopurinol adalah obat yang digunakan untuk menurunkan kadar asam urat dalam darah. Obat ini bekerja untuk menurunkan konsentrasi asam urat dalam darah dan urine sehingga dapat mencegah terjadinya nyeri sendi akibat penumpukan asam urat atau mencegah peningkatan kadar asam urat dalam darah bagi pasien yang sedang menjalani kemoterapi kanker. Dalam penggunaan obat ini HARUS SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa : Awal : 100-300 mg/hari. Pemeliharaan : 200-600 mg/hari. Maksimal : 900 mg/hari. Kondisi ringan : 2-10 mg/kg BB/hari atau 100-200 mg/hari. Kondisi sedang : 300-600 mg/hari. Kondisi berat : 700-900 mg/hari. Anak : 10-20 mg/kg BB/hari\r\n', 'Sesudah makan\r\n', './assets/img/obat/zyloric100mg.jpg'),
(34, 'Zitanid 2 MG 10 Tablet\r\n', 'Otot, Tulang & Sendi', 70400, 'ZITANID 2 MG TABLET merupakan obat yang mengandung Tizanidine. Obat ini digunakan untuk melemaskan otot dari ketegangan, kaku, hingga gerak otot yang sulit dikontrol. Tizanidine bekerja dengan cara menghambat kerja otak dan saraf sehingga memberikan waktu bagi otot untuk rileks atau dilemaskan. Dalam penggunaan obat ini HARUS SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. 3 x sehari 1 tablet\r\n', 'Sesudah makan\r\n', './assets/img/obat/zitanid2mg.jpg'),
(35, 'Ossoral 800 MG 10 Kaplet\r\n', 'Otot, Tulang & Sendi', 49200, 'OSSORAL merupakan obat dengan kandungan Ossein hydroxyapatite, Ca, Phosphorus dalam bentuk kaplet salut selaput. Obat ini digunakan untuk osteoporosis primer, osteoporosis sekunder (karena pengobatan kortikoid, heparin, imobilisasi, rematoid artritis, penyakit hati dan ginjal, hiperparatiroid, osteogenesis imperfecta), pengobatan awal pada pasien dengan meningkatnya risiko osteoporosis, mengatur keseimbangan kalsium dan fosfat selama kehamilan, menyusui dan patah tulang. Dalam penggunaan obat in', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. 1 x sehari 1-2 kapet, Osteoporosis : 2 x sehari 2-4 kaplet, indikasi lainnya : 1 x sehari 1 kaplet\r\n', 'Sesudah makan\r\n', './assets/img/obat/ossoral800.jpg'),
(36, 'KASA STERIL HUSADA 16 CM X 16CM', 'P3K', 12000, 'kasa steril yang digunakan untuk operasi besar/kecil, khitan, penutup luka dan bebat pusar bayi. Produk ini aman digunakan karena disterilisasi dengan iradiasi sinar gamma yang tidak meninggalkan residu bahan kimia pada produk.\r\n', '-', 'Berikan setelah luka telah dicuci\r\n', './assets/img/obat/perban.jpg'),
(37, 'RIVANOL', 'P3K', 5000, 'RIVANOL adalah cairan desinfektan yang di gunakan untuk membersihkan luka.\r\n', 'Sesuai kebutuhan\r\n', 'Bubuhkan rivanol pada kapas, kemudian usapkan pada luka. bisa untuk membasuh luka\r\n', './assets/img/obat/rivanol.jpg'),
(38, 'BETADINE SOLUTION 30 ML', 'P3K', 22100, 'BETADINE SOLUTION merupakan antiseptik luka dengan kandungan Povidone Iodine 10% untuk membunuh kuman penyebab infeksi.', 'Oleskan beberapa kali sehari', 'teteskan pada bagian yang terluka', './assets/img/obat/betadine.jpg'),
(39, 'HANSAPLAST ROLL KAIN 1.25CM X 5M', 'P3K', 12000, 'HANSAPLAST ROLL KAIN 1.25CM X 5M merupakan plester yang di gunakan untuk melindungi luka', '-', 'setelah luka telah ditutupi perban', './assets/img/obat/hansaplast.jpg'),
(40, 'LEUKOSAN STRIP 6 X 75 MM 1 PIECES', 'P3K', 9100, 'Plester luka melindungi dari bakteri', 'Sesuai kebutuhan', 'Buka kemasan, aplikasikan ke daerah yang akan ditutup lukanya.', './assets/img/obat/leukosan.jpg'),
(41, 'CETIRIZINE 10 MG 10 TABLET', 'Alergi', 3000, 'CETIRIZINE merupakan obat generik golongan antihistamin yang berfungsi untuk meredakan gejala alergi seperti mata dan hidung berair, gatal pada mata dan hidung, bersin-bersin, dan gatal pada kulit. Obat ini bekerja dengan cara memblokir zat histamin yang menyebabkan alergi pada tubuh. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa dan anak diatas 12 tahun: 1 tablet, 1 kali per hari', 'Sebelum atau sesudah makan', './assets/img/obat/cetrizine.jpg'),
(42, 'CERINI 10 MG 10 KAPSUL', 'Alergi', 44000, 'CERINI adalah obat yang di gunakan untuk mengobati kondisi alergi (rhinitis perennial, rhinitis alergi musiman dan kronis atau urtikariaidiopatik. Cerini mengandung ceterizine obat anti histamin yang merupakan antagonis kuat dan sangat selektif terhadap histamin perifer H1 reseptor. Dalam penggunaan obat ini HARUS SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa dan anak diatas 12 tahun: 1 tablet, 1 kali per hari', 'Sebelum atau sesudah makan\r\n', './assets/img/obat/cerini.jpg'),
(43, 'CTM 4 MG 12 TABLET', 'Alergi', 2000, 'CTM 4 MG TABLET mengandung zat aktif Chlorpheniramine maleat, obat golongan agonis histamin perifer H1-reseptor. Obat ini digunakan untuk mengatasi gejala alergi seperti rhinitis alergi, urtikaria, bersin-bersin, mata berair, gatal pada mata, hidung, tenggorokan atau kulit. Obat ini dapat menyebabkan kantuk. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Sesuai petunjuk dokter atau : Dewasa 3-4 kali/hari 1/2-1 tablet, Anak 3-4 kali/hari 1/4-1/2 tablet\r\n', 'Diberikan bersama atau tanpa makanan', './assets/img/obat/ctm.jpg'),
(44, 'HISTRINE 10 MG 10 TABLET', 'Alergi', 50200, 'HISTRINE 10 MG TABLET merupakan obat dengan kandungan Cetirizine HCl yaitu golongan antihistamin yang berfungsi untuk meredakan gejala alergi seperti mata dan hidung berair, gatal pada mata dan hidung, bersin-bersin, dan gatal-gatal. Obat ini bekerja dengan cara memblokir zat histamin yang menyebabkan alergi pada tubuh. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa dan anak diatas 12 tahun: 1 tablet, 1 kali per hari\r\n', 'Sebelum atau sesudah makan', './assets/img/obat/histrine.jpg'),
(45, 'TELFAST OD 120 MG 10 TABLET', 'Alergi', 88000, 'TELFAST OD 120 MG 10 TABLET merupakan obat dengan kandungan Fexofenadine HCl. Fexofenadine HCl merupakan golongan obat antihistamin generasi kedua. Obat ini bekerja dengan cara memblokir selektif aktivasi reseptor H1 oleh histamin sehingga terjadi pencegahan gejala alergi. Obat ini sedikit menembus sawar darah otak sehingga sedikit memberikan efek sedasi. Fexofenadine HCl digunakan untuk menghilangkan gejala alergi seperti rinitis alergi dan urtikaria idiopatik kronik. Dalam penggunaan obat ini ', 'Fexofenadine HCl 120 mg', 'Berikan sebelum makan. Jangan diberikan bersama jus buah', './assets/img/obat/telefast.jpg'),
(46, 'KONDOM DUREX PERFORMA ISI 3', 'kontrasepsi & hormon', 20000, 'KONDOM DUREX PERFORMA ISI 3 merupakan alat kontrasepsi yang di gunakan oleh pria\r\n', 'Sesuai kebutuhan. Digunakan saat berhubungan intim', 'Digunakan pada kelamin pria saat berhubungan intim', './assets/img/obat/durex.jpg'),
(47, 'KONDOM SUTRA OK ISI 12', 'kontrasepsi & hormon', 24000, 'KONDOM SUTRA OK ISI 12 merupakan alat kontrasepsi yang di gunakan oleh pria\r\n', 'Sesuai kebutuhan. Digunakan saat berhubungan intim', 'Digunakan pada kelamin pria saat berhubungan intim', './assets/img/obat/sutra.jpg'),
(48, 'PRIMOLUT N 5 MG 10 TABLET', 'kontrasepsi & hormon', 62200, 'PRIMOLUT N merupakan obat dengan kandungan Norethisterone, yang merupakan hormon progesteron. Obat ini digunakan untuk pendarahan disfungsional, amenore primer dan sekunder, sindrom pra-menstruasi, mastopati siklik, pengaturan waktu menstruasi, endometriosis. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Pendarahan disfungsional : 3 x per hari 1 tablet selama 10 hari, maksimal 30 hari. Amenore primer dan sekunder : 1-2 x sehari 1 tablet selama 10 hari. Untuk merangsang pendarahan siklus : 2 x sehari 1 tablet dimulai pada hari ke 16 sampai dengan 25 dari siklus menstruasi. Sindrom pra-menstruasi : 1 - 3 x sehari 1 tablet selama fase luteal dari siklus. Pengaturan Haid : 2-3 x sehari 1 tablet selama 10-14 hari dimulai 3 hari sebelum menstrua', 'Berikan sesudah makan', './assets/img/obat/primolut.jpg'),
(49, 'DIANE 35 TABLET', 'kontrasepsi & hormon', 127000, 'DIANE-35 TABLET adalah obat kontrasepsi yang mengandung kombinasi Cyproterone acetate 2 mg dan Ethinyl estradiol 0.035 mg. Obat ini digunakan sebagai kontrasepsi oral. Obat Diane-35 juga dapat digunakan untuk mengobati wanita dengan masalah jerawat yang parah, serta dapat menangani masalah lain seperti seborrhea atau hirsutisme ringan. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. 1 x sehari 1 tablet dimulai pada hari ke-1 siklus haid selama 21 hari diikuti masa istirahat selama 7 hari.\r\n', 'Sebelum atau sesudah makan', './assets/img/obat/diane.jpg'),
(50, 'KONDOM FIESTA ULTRA THIN ISI 3', 'kontrasepsi & hormon', 10500, '-', 'Sesuai kebutuhan. Digunakan saat berhubungan intim', 'Digunakan pada kelamin pria saat berhubungan intim', './assets/img/obat/fiesta.jpg'),
(51, 'Amoxicillin 500 MG 10 Kaplet', 'Antibiotik', 32500, 'AMOXICILLIN merupakan obat antibiotik generik turunan Penisilin dengan aktivitas antibakteri spektrum luas. Obat ini bersifat bakterisid yang efektif terhadap bakteri Gram negatif dan Gram positif seperti Staphylococci, Streptococci, Enterococci, S. pneumoniae, N. gonorrhoeae, H influenzas, E. coli, dan P. mirabiis. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa 250 sampai 500 mg tiap 8 jam. Anak 20 mg/kgBB/hari terbagi tiap 8 jam. Infeksi berat diberikan dosis ganda. Jika akut diberikan dalam 2 sampai 3 g dosis tunggal.\r\n', 'Sesudah makan\r\n', './assets/img/obat/amoxicillin500mg.jpg'),
(52, 'Azithromycin 500 MG 10 Kaplet', 'Antibiotik', 39400, 'AZITHROMYCIN adalah obat antibiotik generik golongan makrolida yang aktivitasnya terhadap bakteri gram positif dan gram negatif. Obat ini bekerja dengan cara mengikat sub unit 50s dari ribosom bakteri sehingga menghambat translasi mRNA. Dengan demikian sistesis protein akan terganggu sehingga pertumbuhan bakteri akan terhambat. Obat ini digunakan untuk pengobatan infeksi yang disebabkan oleh H. influenzae, M. catarrhalis, S. pneumoniae, C. pneumoniae, H. influenzae, Streptococcus pyogenes, S. au', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dws (termasuk usia lanjut) STD 1 g dosis tunggal oral. Semua indikasi lainnya 500 mg 1 x/hari selama 3 hari. Anak 10 mg/kg BB/hari dosis tunggal selama 3 hari.\r\n', 'Dapat diberkan bersama makanan untuk mengurangi rasa tidak nyaman pada GI\r\n\r\n', './assets/img/obat/azithromycin.jpg'),
(53, 'Cefixime 200 MG 10 Kapsul', 'Antibiotik', 41500, 'CEFIXIME 200 MG KAPSUL merupakakan obat generik yang mengandung Cefixime 200 mg per tablet. Cefixime adalah antibiotik golongan cephalosporin generasi ketiga. Cefixime merupakan antibiotik yang memiliki spektrum luas, aktif terhadap bakteri gram negatif mapun gram positif. Antibiotik ini digunakan untuk mengobati infeksi saluran kemih tanpa komplikasi, otitis media, faringiris dan tonsilitis, serta bronkitis akut dan kronis dengan eksaserbasi akut. Obat ini bekerja sebagai bakterisidal dengan me', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Dewasa dan anak dengan BB 30 kg atau lebih : 50-100 mg, 2 kali sehari. Untuk infeksi yang berat, dosis dapat ditingkatkan sampai 200 mg diberikan dua kali sehari.\r\n', 'Dikonsumsi sebelum atau sesudah makan. Dapat diberikan bersama makanan untuk mengurangi rasa tidak nyaman pada saluran pencernaan.\r\n', './assets/img/obat/cefixime.jpg'),
(54, 'Levofloxacin  500 MG 10 tablet', 'Antibiotik', 41500, 'LEVOFLOXACIN adalah antibiotik golongan fluorokuinolon yang mempunyai spektrum luas, aktif terhadap bakteri gram negatif maupun positif. Obat ini untuk mengobati infeksi bakteri seperti infeksi saluran kemih, pneumonia, bronchitis, sinusitis, infeksi kulit, jaringan lunak dan infeksi prostat. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Sinusitis bakterial akut - Dewasa : 500 mg sekali sehari selama 10-14 hari Eksaserbasi bakterial akut pada bronkitis kronis - Dewasa : 500 mg sekali sehari selama 7-10 hari Pyelonefritis - Dewasa : 500 mg sekali sehari selama 7-10 hari Pneumonia - Dewasa: 500 mg sekali sehari selama 7-14 hari Infeksi kulit berat - Dewasa : 500 mg sehari sekali selama 7-14 hari\r\n', 'Dikonsumsi sebelum atau sesudah makan\r\n', './assets/img/obat/levofloxacin.jpg'),
(55, 'Flagystatin 5 ovula', 'Antibiotik', 90000, 'FLAGYSTATIN OVULA adalah obat ovula dengan kandungan Metronidazole dan Nystatin. Metronidazole merupakan obat antibiotik yang bersifat bakterisid. Obat ini efektif terhadap amoeba dan Trichomonas vaginalis (trikomonasid). Nystatin merupakan obat antifungal. Obat ini bekerja dengan cara mengikat sterol pada membran sel jamur sehingga menjadi bocor dan keluarlah komponen-komponen penting dalam sel jamur. Dengan demikian nystatin dapat menghentikan pertumbuhan jamur (fungistatik) atau bahkan membun', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. 1 Ovula perhari selama 7-10 hari, dapat dikombinasi dengan Flagyl tablet 250 mg, 2 kali per hari.\r\n', 'Masukkan kedalam vagina. Gunakan sebelum tidur.\r\n', './assets/img/obat/flagystatin.jpg'),
(56, 'Hydrocortison Cream 2.5% 5 GR', 'Kulit', 28000, 'HYDROCORTISON CREAM adalah obat adrenokortikal steroid yang memiliki sifat anti-inflamasi, anti alergi dan anti pruritus pada jaringan kulit. Hydrocortison di gunakan untuk mengobati eksim, inflamasi, kemerahan,serta gatal-gatal pada kulit, beberapa jenis infeksi kulit yang dapat diobati contohnya dermatitis alergi, dermatitis kontak, dermatitis atopi, pruritus anogenital, neurodermatitis. Dalam penggunaan obat ini HARUS SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Oleskan pada kulit yang bermasalah 2-3 kali per hari.\r\n', 'oleskan tipis pada bagian yang membutuhkan', './assets/img/obat/Hydrocortison.jpg'),
(57, 'Benzolac CL Gel 10 G', 'Kulit', 36000, 'BENZOLAC CL GEL adalah obat yang mengandung Clindamycin Phosphate dan Benzoyl Peroxide. Obat ini merupakan antibiotik topikal untuk mengobati jerawat. Clindamycin merupakan antibiotika golongan lincosamida semisintetik yang bersifat bakteriostatik dan Benzoyl peroxide merupakan senyawa yang memiliki efek keratolitik ringan dan aktivitas antimikroba. Keduanya aktif terhadap kuman Propionibacterium acnes, organisme yang berhubungan dengan akne vulgaris (jerawat). Dalam penggunaan obat ini harus SE', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Oleskan gel 2 x sehari pada jerawat\r\n', 'Hindari kontak dengan mata, mulut, membran mukosa lainnya', './assets/img/obat/Benzolac.jpg'),
(58, 'Bioplancenton Gel 15 G', 'Kulit', 19400, 'BIOPLACENTON merupakan obat yang mengandung Placenta Extract dan Neomycin sulfate. Obat ini biasa digunakan untuk mengobati luka bakar, luka dengan infeksi, serta luka kronik dan jenis luka yang lain. Ekstrak plasenta bekerja dengan memicu pembentukan jaringan baru dan untuk wound healing, sedangkan neomycin bekerja dengan mencegah atau mengatasi infeksi bakteri Gram negatif pada area luka. Dalam penggunaan obat ini harus SESUAI DENGAN PETUNJUK DOKTER.\r\n', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Oleskan 4-6 x sehari atau sesuai kebutuhan pada area luka.\r\n', 'Hindari kontak dengan mata, mulut, membran mukosa lainnya', './assets/img/obat/Bioplancenton.jpg'),
(59, 'Caladine Lotion 60 ML', 'Kulit', 13200, 'CALADINE LOTION 60 ML adalah lotion yang mengandung Calamine, Zinc Oxyde dan Diphenhydramine HCL, Caladine lotion ini berbahan dasar air, sehingga sangat cocok untuk daerah tropis seperti Indonesia. CALADINE LOTION bermanfaat mengobati gatal karena biang keringat, udara panas, gigitan serangga, dan juga dapat dijadikan sebagai anti-alergi, anti-septik, atau untuk penyejuk kulit.\r\n', 'Dewasa dan anak : Bersihkan bagian kulit yang gatal lalu oleskan 2-4 kali sehari setelah mandi.\r\n', 'Bersihkan bagian kulit yang gatal lalu oleskan 2-4 kali sehari, sebaiknya digunakan sehabis mandi pagi dan sore.\r\n', './assets/img/obat/Caladine.jpg'),
(60, 'Benoson M Cream 5 G', 'Kulit', 63000, 'BENOSON M adalah obat yang mengandung Miconazole nitrate dan Betametasone valerate. Obat ini digunakan untuk mengatasi penyakit kulit termasuk eksim dan dermatitis. Betametasone valerate merupakan obat yang termasuk golongan kortikosteroid, bekerja dengan cara mencegah dan mengendalikan peradangan dengan mengendalikan laju sintesis protein, menekan migrasi leukosit polimorfonuklear dan fibroblast, sedangkan miconazole nitrate merupakan antijamur golongan imidazole. Dalam penggunaan obat ini HARU', 'PENGGUNAAN OBAT INI HARUS SESUAI DENGAN PETUNJUK DOKTER. Oleskan krim pada bagian kulit yang sakit/radang 2-3 x sehari\r\n', 'Krim dioleskan pada area kulit yang sakit/radang\r\n', './assets/img/obat/Benoson.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(30) NOT NULL,
  `name` varchar(30) NOT NULL,
  `email` varchar(30) NOT NULL,
  `address` varchar(100) NOT NULL,
  `birth` date NOT NULL,
  `password` varchar(30) NOT NULL,
  `pic` varchar(100) NOT NULL,
  `gender` varchar(30) NOT NULL,
  `no_hp` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `name`, `email`, `address`, `birth`, `password`, `pic`, `gender`, `no_hp`) VALUES
(46, 'Dimitri Irfan Dzidny', 'dimitriirfan@gmail.com', 'Jalan Haji Naimun no 12A Pondok Pinang Kebayoran Lama ', '1999-11-12', 'dimitri27', './assets/img/profile/doctor.jpg', 'male', '081283083410'),
(51, 'test', 'test@gmail.com', 'test', '1212-11-12', 'test', 'defaultpic.jpg', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `drug`
--
ALTER TABLE `drug`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`,`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `drug`
--
ALTER TABLE `drug`
  MODIFY `id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(30) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
